server:
  port: 5555

spring:
  application:
    name: gateway-module
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "http://localhost:3000"
            allowedMethods:
              - GET
              - POST
            allowedHeaders: "*"
      routes:
        - id: core-service-module
          uri: http://localhost:8189/
          predicates:
            - Path=/core/**
          filters:
            - StripPrefix=1
            - PrefixPath=/core
#            - JwtAuthFilter

jwt:
  secret: h4f8093h4f983yhrt9834hr0934hf0hf493g493gf438rh438th34g34g

#logging:
#  level:
#    reactor:
#      netty: TRACE
#    org:
#      springframework:
#        cloud:
#          gateway: TRACE
